"""
Dictionaries that map the EPA spreadsheet names to the EPAVehicle model field names.
Used by management.py to import the EPA data into the database.
"""

# Note 2006 is missing the 'REL DT' field. manually added
epa_2006_to_2009 = {
    'CLASS': 'vehicle_class',
    'MFR': 'manufacturer',
    'CAR LINE': 'model',
    'DISPLACEMENT': 'displacement_in_liters',
    'NUMB CYL': 'number_of_cylinders',
    'TRANS': 'transmission',
    'DRIVE SYS': 'drive_axle_type',
    'INDEX NUMB': 'index_number',
    'CITY MPG (GUIDE)': 'city_mpg_guide',
    'HWY MPG (GUIDE)': 'highway_mpg_guide',
    'COMB MPG (GUIDE)': 'combined_mpg_guide',
    'UNRND CITY (EPA)': 'unrated_city_epa',
    'UNRND HWY (EPA)': 'unrated_hwy_epa',
    'UNRND COMP (EPA)': 'unrated_combined_epa',
    'FUEL TYPE': 'fuel_type',
    'GUZLR': 'gas_guzzler',
    'TURBO': 'turbocharger',
    'SPCHGR': 'supercharger',
    'AVG 2D PASS VOL': 'two_door_passenger_volume',
    'AVG 2D LUGG VOL': 'two_door_luggage_volume',
    'AVG 4D PAS VOL': 'four_door_passenger_volume',
    'AVG 4D LUGG VOL': 'four_door_luggage_volume',
    'AVG HB PAS VOL': 'hatchback_passenger_volume',
    'AVG HB LUGG VOL': 'hatchback_luggage_volume',
    'ANL FL CST': 'annual_fuel_cost',
    'ENG BLK TXT': 'engine_block',
    'TRANS DESC TXT': 'transmission_description',
    'VLVS PER CYL': 'valves_per_cylinder',
    'CLS': 'class_code',  # numeric code for sorting vehicle_class
    'REL DT': 'release_date',
    '5C CODE': 'test_method', # DERIVED or 5CYCLE
}

epa_1998_to_2005 = {
    'Class': 'vehicle_class',
    'Manufacturer': 'manufacturer',
    'carline name': 'model',
    'displ': 'displacement_in_liters',
    'cyl': 'number_of_cylinders',
    'trans': 'transmission',
    'drv': 'drive_axle_type',
    'bidx': 'index_number',
    'cty': 'city_mpg_guide',
    'hwy': 'highway_mpg_guide',
    'cmb': 'combined_mpg_guide',
    'ucty': 'unrated_city_epa',
    'uhwy': 'unrated_hwy_epa',
    'ucmb': 'unrated_combined_epa',
    'fl': 'fuel_type',
    'G': 'gas_guzzler',
    'T': 'turbocharger',
    'S': 'supercharger',
    '2pv': 'two_door_passenger_volume',
    '2lv': 'two_door_luggage_volume',
    '4pv': 'four_door_passenger_volume',
    '4lv': 'four_door_luggage_volume',
    'hpv': 'hatchback_passenger_volume',
    'hlv': 'hatchback_luggage_volume',
    'fcost': 'annual_fuel_cost',
    'eng dscr': 'engine_block',
    'trans dscr': 'transmission_description',
    'vpc': 'valves_per_cylinder',
    'cls': 'class_code',  # numeric code for sorting vehicle_class
    'REL DT': 'release_date',
    '5C CODE': 'test_method', # DERIVED or 5CYCLE
}

# fields from dbf not added to model:
#  - CITYE, HWYE, ENERGYCMB (all values are 0 in dbf)
#  - FUELPRICE,N,5,2 (dynamically updated on EPA website?)
epa_dbf_1985_to_2009 = {
    'YEAR,C,4': 'year',
    'VCLASS,C,29': 'vehicle_class',
    'NEWMAKE,C,40': 'manufacturer',
    'NEWMODEL,C,40': 'model',
    'DISPL,C,4': 'displacement_in_liters',
    'CYLINDERS,C,4': 'number_of_cylinders',
    'TRANY,C,40': 'transmission',
    'DRIVE,C,30': 'drive_axle_type',
    'ID,C,6': 'index_number',
    'CITY,N,11,0': 'city_mpg_guide',
    'HIGHWAY,N,11,0': 'highway_mpg_guide',
    'COMBINED,N,11,0': 'combined_mpg_guide',
    'UCITY,N,8,4': 'unrated_city_epa',
    'UHIGHWAY,N,8,4': 'unrated_hwy_epa',
    'UCOMBINED,N,8,4': 'unrated_combined_epa',
    'FUELTYPE,C,40': 'fuel_type',
    'GUZZLER,C,2': 'gas_guzzler',
    'TCHARGER,C,2': 'turbocharger',
    'SCHARGER,C,2': 'supercharger',
    'PV2,N,11,0': 'two_door_passenger_volume',
    'LV2,N,11,0': 'two_door_luggage_volume',
    'PV4,N,11,0': 'four_door_passenger_volume',
    'LV4,N,11,0': 'four_door_luggage_volume',
    'HPV,N,11,0': 'hatchback_passenger_volume',
    'HLV,N,11,0': 'hatchback_luggage_volume',
    'ENG_DSCR,C,40': 'engine_block',
    'TRANS_DSCR,C,15': 'transmission_description',
    'VPC,C,2': 'valves_per_cylinder',

    # not sure what these are yet...
    'CITYA,N,11,0': 'citya',
    'HIGHWAYA,N,11,0': 'highwaya',
    'COMBINEDA,N,11,0': 'combineda',
    'UCITYA,N,8,4': 'ucitya',
    'UHIGHWAYA,N,8,4': 'uhighwaya',
    'UCOMBINEDA,N,8,4': 'ucombineda',
    'CITY08,N,3,0': 'city08',
    'HIGHWAY08,N,3,0': 'highway08',
    'COMB08,N,3,0': 'combined08',
    'CITYA08,N,3,0': 'citya08',
    'HIGHWAYA08,N,3,0': 'highwaya08',
    'COMBA08,N,3,0': 'combineda08',
    'COST08,N,5,0': 'cost08',
    'COSTA08,N,5,0': 'costa08',
    
    # field to ignore:
    'FUELPRICE,N,5,2': None,
    'CITYE,N,11,0': None,
    'HWYE,N,11,0': None,
    'ENERGYCMB,N,11,0': None,
}

from vehicle.models import NO_TRANSMISSION, AUTOMATIC, MANUAL, VBR

TRANSMISSION_STRING_MAPPINGS = (
    # (transmission, transmission_speed, epa string)
    (NO_TRANSMISSION, 0, 'No Transmission'),
    (AUTOMATIC, 4, 'Automatic (S4)'),
    (AUTOMATIC, 5, 'Automatic (S5)'),
    (AUTOMATIC, 6, 'Automatic (S6)'),
    (AUTOMATIC, 7, 'Automatic (S7)'),
    (AUTOMATIC, 8, 'Automatic (S8)'),
    (AUTOMATIC, VBR, 'Automatic (variable gear ratios)'),
    (AUTOMATIC, 3, 'Automatic 3-spd'),
    (AUTOMATIC, 4, 'Automatic 4-spd'),
    (AUTOMATIC, 5, 'Automatic 5-spd'),
    (AUTOMATIC, 6, 'Automatic 6-spd'),
    (AUTOMATIC, 7, 'Automatic 7-spd'),
    (AUTOMATIC, 7, 'Auto(A7)'),
    (AUTOMATIC, 3, 'C5'),
    (MANUAL, 3, 'Manual 3-spd'),
    (MANUAL, 4, 'Manual 4-spd'),
    (MANUAL, 5, 'Manual 5-spd'),
    (MANUAL, 6, 'Manual 6-spd'),
)

VEHICLE_CLASS_MAPPINGS = (
    (1, 'Compact Cars'),
    (3, 'Large Cars'),
    (2, 'Midsize Cars'),
    (8, 'Midsize Station Wagons'),
    (9, 'Midsize-Large Station Wagons'),
    (0, 'Minicompact Cars'),
    (4, 'Minivan - 2WD'),
    (4, 'Minivan - 4WD'),
    (5, 'Small Pickup Trucks'),
    (5, 'Small Pickup Trucks 2WD'),
    (5, 'Small Pickup Trucks 2wd'),
    (5, 'Small Pickup Trucks 4WD'),
    (7, 'Small Station Wagons'),
    (10, 'Special Purpose Vehicle 2wd'),
    (10, 'Special Purpose Vehicle 4wd'),
    (10, 'Special Purpose Vehicles'),
    (11, 'Sport Utility Vehicle - 2WD'),
    (11, 'Sport Utility Vehicle - 4WD'),
    (11, 'Sport Utility Vehicle 2WD'),
    (6, 'Standard Pickup Trucks'),
    (6, 'Standard Pickup Trucks 2WD'),
    (6, 'Standard Pickup Trucks 2wd'),
    (6, 'Standard Pickup Trucks 4WD'),
    (6, 'Standard Pickup Trucks 4wd'),
    (0, 'Subcompact Cars'),
    (1, 'Two Seaters'),
    (12, 'Vans'),
    (12, 'Vans, Cargo Type'),
    (12, 'Vans, Passenger Type'),
)